### ISSUE TITLE
Exception if API endpoint does not return JSON

### ISSUE THREAD

**Issue by ajoah** [Ubiquiti-App/UCRM-Plugin-SDK#10]
Hi,

I saw that you always use json_decode on get api response : https://github.com/Ubiquiti-App/UCRM-Plugin-SDK/blob/685cec5a4e5d3127b168da3f64f96418d5c67900/src/UcrmPluginSdk/Service/UcrmApi.php#L113-L124
But there is a problem : all endpoints does not return a json systematically. 

For example, this one returns a pdf file : https://ucrm.docs.apiary.io/#reference/invoices/invoicesidpdf/get

Call this endpoint causes an exception even if the response is correct.

`Fatal error: Uncaught Ubnt\UcrmPluginSdk\Exception\JsonException: Syntax error in /data/ucrm/data/plugins/myplugin/vendor/ubnt/ucrm-plugin-sdk/src/UcrmPluginSdk/Util/Json.php:45`

Maybe you can change your code to something like this : 
```php
    public function get(string $endpoint, array $query = [])
    {
        $response = $this->request(
            'GET',
            $endpoint,
            [
                'query' => $query,
            ]
        );
        if(current($response->getHeader('Content-Type')) === 'application/json'){
            return Json::decode((string) $response->getBody());
        }

        return (string) $response->getBody();
    }
```

**Comment by keksa** [comment]
Hello @ajoah, that's a good point, feel free to send a PR with this change. ;)

**Comment by ajoah** [comment]
Wow, quick answer ! It is done :)
