### ISSUE TITLE
Menu link parameters error

### ISSUE THREAD

**Issue by Fuitad** [Ubiquiti-App/UCRM-Plugin-SDK#15]
Hey! In the documentation, it is stated that if you provide a parameters object for a menu item (inside manifest.json), it will be used in the query string. The example is 

> For example if `parameters` are `{"hook": "main"},` then link is `/_plugins/<plugin-name>/public.php?hook=main`.

However, when I do this one my own server, it seems to be handled differently. The result becomes:

> `/_plugins/<plugin-name>/public?parameters%5Bhook%5D=main`

Is this a bug? I'm running 2.16.4. Thanks!

**Comment by keksa** [comment]
Hi @Fuitad, I think the result you posted is the CRM URL, you should look at the URL, that the plugin's iframe receives.

**Comment by Fuitad** [comment]
\*facepalm\*

thanks!
