### ISSUE TITLE
Best way to store data?

### ISSUE THREAD

**Issue by Fuitad** [Ubiquiti-App/UCRM-Plugin-SDK#16]
I want to create a plugin that will introduce new features inside the UCRM application, not just leverage what's already in there. From what I can tell, the plugins are basically little PHP applications that run on the side and use the API to do their job. This means that there is no way to access the UCRM database directly (which is not totally a bad thing).

However, I'm curious to know what's the recommended way to store data. I know that the PHP installation inside ubnt/ucrm-billing has the SQLite module. Should we be using sqlite databases and store it inside the /data folder of the plugin? This doesn't seem like the best way to have a stable and scalable data storage.

So what should I be doing?

**Comment by keksa** [comment]
Hi @Fuitad, you got it right. The best way I can think of is to use an SQLite db and put it in the data directory. This way it will be included in CRM backups and protected between plugin updates.

The only other way would be to use an external database service and connect to it, but this would make the setup for plugin users more difficult.

You can read some more information here https://community.ui.com/questions/UCRM-v2-16-0-Plugins-Problems-using-php-pdo-pgsql/028da286-fa18-437a-82bf-6fbf4aa1f6dd#answer/7832b13f-dcb0-4964-88ee-233008a5e738

**Comment by Fuitad** [comment]
Thanks!
