### ISSUE TITLE
Request for addition in the /users/admins API

### ISSUE THREAD

**Issue by Fuitad** [Ubiquiti-App/UCRM-Plugin-SDK#17]
Heya,

I know this is probably not the right place for this request but since there's no repo for the API itself, I'm hoping it will be ok.

I'd like to know if, in a future version, you could add the "active" status for admins in the API endpoint /users/admins. This flag is returned for customers but not for admins. 

It would be pretty useful on our ends. Thanks!

**Comment by enumag** [comment]
Fixed for UCRM 2.16.5.
